apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-vuejs-deployment
spec:
  selector:
    matchLabels:
      app: frontend-vuejs
  template:
    metadata:
      labels:
        app: frontend-vuejs
    spec:
      containers:
        - name: frontend-vuejs
          image: mhmdio/frontend-vuejs:v1.0.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
